import esbuild from 'esbuild';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
https://github.com/ozntel/oz-calendar
*/
`;

const builtins = (await import('builtin-modules')).default;

const outDir = path.join(__dirname, 'release', 'oz-calendar');

if (!fs.existsSync(outDir)) {
	fs.mkdirSync(outDir, { recursive: true });
}

await esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: [path.join(__dirname, 'src', 'main.ts')],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins,
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: false,
	treeShaking: true,
	outfile: path.join(outDir, 'main.js'),
});

fs.copyFileSync(path.join(__dirname, 'manifest.json'), path.join(outDir, 'manifest.json'));
fs.copyFileSync(path.join(__dirname, 'styles.css'), path.join(outDir, 'styles.css'));

console.log('\nBuild complete! Output directory:');
console.log('  ' + outDir);
console.log('\nInstallation files:');
console.log('  - main.js');
console.log('  - manifest.json');
console.log('  - styles.css');
